### ISSUE TITLE
Language specific strings for ticket creation

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#60]
**Is your feature request related to a problem? Please describe.**
Due to usage of this adapter for german Zendesk installations, it is a wish to have the strings in ticket creation subject in current selected language in Zendesk.

Currently, the text strings  for the subject in Zendesk are hard-coded in englisch here:
https://github.com/voicefoundryap/amazon-connect-for-zendesk/blob/master/src/assets/scripts/topBar/newTicket.js 
line 94ff

**Describe the solution you'd like**
Please make it possible to have this part variable by current browser language or Zendesk agent language selected and create tickets with the current language instead only provide english.

If possible, make the subject text completly customizable with placeholders to be dynamically replaced at time the ticket was created.

**Suggestions**
Cover it as seperate strings in a new lang file like this:
 amazon-connect-for-zendesk/src/translations/en.json 
Seperate strings for 
- Outgoing call to {callno}
- Incoming call from {callno}
- Callback to {callno}
and also for comments:
- Ticket created by an ${session.outbound ? 'outgoing call to' : 'incoming call from'} ${user.name}`,

**Comment by agroblervf** [comment]
Thanks @AlexD1979 for submitting this feature request. We already have plans to include internationalisation in an upcoming release. We'll track the progress and give updates in this issue.
For the customisation of the subject line with placeholders I think this is a great idea, but it would be better to track it as a separate issue.
