### ISSUE TITLE
Enhanced Client-side Logging

### ISSUE THREAD

**Issue by agroblervf** [voicefoundryap/amazon-connect-for-zendesk#61]
**Is your feature request related to a problem? Please describe.**
When an intermittent issues arise it is hard to troubleshoot without being able to reproduce consistently. 

**Describe the solution you'd like**
Implement a tooling which would enable collecting client side logs (browser console logs) and other data and make them available to development team for analysis.

**Describe alternatives you've considered**
Currently we need to have an online session with the user to catch the issue when it happens which is very unpractical.

**Additional context**
Have the ability to turn the enhanced logging on and off, per each user. Have the logging sessions searchable by the agent, so problem behaviour can be narrowed down quickly.

**Comment by Scifire** [comment]
@karl-mentzer-vf Why is this closed? Will this not be implemented? That would make things a lot easier if client side debugging would be available.

**Comment by karl-mentzer-vf** [comment]
@Scifire we are moving requests to Jira. This includes the product enhancements and bugs. 

The new process will be updated on our Zendesk Marketplace Application page when Zendesk Marketplace team update this. We are expecting it any day now. 

Please note: Product Enhancements are controlled by Zendesk for this application and need to be accepted there first. No agreement to develop is made without Zendesk Approval.

**Comment by Scifire** [comment]
@karl-mentzer-vf you should definitely explain that on the README how this application is developed. That would make lot´s of things easier.

**Comment by karl-mentzer-vf** [comment]
Yes the ReadMe will be updated.
