### ISSUE TITLE
[New feature] Logout agents on closw browser 

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#64]
**Is your feature request related to a problem? Please describe.**
If you where logged in in Zendesk and also in status available in Amazon Connect and you shutdown the PC, the agent will not be logged out from Amazon Connect and the user session stay active in Connect with status available. 

**Describe the solution you'd like**
If the browser where closed, or the user logged out from Zendesk, the CTI should logout also the agent in the background from Amazon Connect. This prevents calls to be routed to this "ghost agents" in the background and the caller have not to wait more time 

**Describe alternatives you've considered**
See Amazon Connect suggested solution : https://aws.amazon.com/premiumsupport/knowledge-center/connect-agent-status-offline-ccp/

**Comment by agroblervf** [comment]
Thanks @AlexD1979, we will put this feature on our road map.

**Comment by karl-mentzer-vf** [comment]
Submitted to Zendesk for approval to develop

**Comment by Scifire** [comment]
@karl-mentzer-vf  why the issue is closed? It is still open and not declined.

**Comment by karl-mentzer-vf** [comment]
@Scifire the issue is closed as it has been submitted to Zendesk via the agreed process which Zendesk and VoiceFoundry have contractually agreed. 

We are tracking all feature requests via an agreed process.

**Comment by Scifire** [comment]
@karl-mentzer-vf  Why does the issue not stay open until a decision is made? So it is a surprise what happens behind closed doors regarding this and if it ever will be implemented or not?

**Comment by karl-mentzer-vf** [comment]
@Scifire your comments are not appreciated or in accordance with the community T&Cs. 

Please provide helpful comments or refrain from commenting.

**Comment by Scifire** [comment]
@karl-mentzer-vf I´m asking questions to understand how things could go forward with this app. But it seems you are not interesset in any improvements.
Understood.

**Comment by karl-mentzer-vf** [comment]
Per issue #61 

We are moving requests to Jira. This includes the product enhancements and bugs.

The new process will be updated on our Zendesk Marketplace Application page when Zendesk Marketplace team update this. We are expecting it any day now.

Please note: Product Enhancements are controlled by Zendesk for this application and need to be accepted there first. No agreement to develop is made without Zendesk Approval.
