### ISSUE TITLE
[New feature] 2nd Ringtone for Agent off headset

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#65]
**Is your feature request related to a problem? Please describe.**
If the agent drops the headset and on PC works in a different Tab and Application inside the Browser, the agent does not recordnize the incoming call ring tone

**Describe the solution you'd like**
Implement 2nd ring tone device like you described in your blog article.

**Describe alternatives you've considered**
Bring the Zendesk Window / Tab in Foreground when ringing or modal or desktop notification in Firefox for incoming call.

**Additional context**
You have already the solution =;o)  https://blog.voicefoundry.com/blog/contact-center-agent-notification-secondary-ringtone

**Comment by agroblervf** [comment]
Thanks @AlexD1979 for this request and also for the link to solution :). We've put this feature on our road map.

**Comment by karl-mentzer-vf** [comment]
Submitted to Zendesk for approval to build
