### ISSUE TITLE
[New feature] Contact Attributes filter for selecting what to add to comments to Zendesk Ticket

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#78]
**Is your feature request related to a problem? Please describe.**
During call flows the user may collect a lot of contact attributes in the CTR. And this contact attributes may contain sensitive data or not ticket relevant informations, just routing helping parameters etc- As this attributes are 1:1 attached as a comment to a ticket, all this informations are persistet in tickets and the comment can be very huge with unneeded informations.

**Describe the solution you'd like**
Introduce a naming schema for contact attributes to be respected in Zendesk tickets to give the contact flow control, which informations will be transferred to Zendesk tickets.

**Additional context**
e.g. all contact attributes prefixed with vfzd_  or zd_  will be transferred to the comments (includeding as today the additional stuff like contact ID, Agent name, phone number, this may not be touched)

**Comment by karl-mentzer-vf** [comment]
Hi @AlexD1979 - Thanks for the feedback. Let me discuss with the Zendesk if they would like to accept this change. This will likely be resolved in the coming months with some new features coming from Zendesk.
