### ISSUE TITLE
[New feature] Connect Chat options with Zendesk Guide

### ISSUE THREAD

**Issue by kyle-moeller** [voicefoundryap/amazon-connect-for-zendesk#79]
**Is your feature request related to a problem? Please describe.**
Currently, the Zendesk Guide only allows for a widget of Zendesk Chat to be placed on it for customer use. This hinders Amazon Connect from using its native chat widget, or any customized Connect Chat widget that might be created. 

**Describe the solution you'd like**
Ideally, a change would be implemented that would allow developers to insert an iframe src URL on the Zendesk Guide page. Other considerations: passing auth credentials if the site user is authenticated which could allow for a customized IVR experience, ability to redirect to the appropriate Zendesk Guide help page (could also just have formatting and display the URL), would likely be in a similar position/alignment as the existing Zendesk Chat widget. 

**Describe alternatives you've considered**
No real alternative at this time as Connect Chat is not a supported channel.

**Comment by karl-mentzer-vf** [comment]
Hi Kyle, the feature for Amazon Chat is being developed in v2.3 and will be released via Public GA release.
