### ISSUE TITLE
Feature to get items in a user's custom field

### ISSUE THREAD

**Issue by Logical-KawashimaKenji** [voicefoundryap/amazon-connect-for-zendesk#89]
Using Amazon Connect contact flow,
I want to get an item on a user's custom field.
Is there a way?

(The red line part of the attached image)
![image](https://user-images.githubusercontent.com/98224835/172750654-36c1cdf1-6138-4f59-8d9e-bad740d22f95.png)

**Comment by Logical-KawashimaKenji** [comment]
![image](https://user-images.githubusercontent.com/98224835/172965481-11c240a5-35dc-4873-a7c6-26589fd233c5.png)

Sorry.
I do not have permission to view this Confluence article...

**Comment by agroblervf** [comment]
Apologies @Logical-KawashimaKenji, that was a wrong link - please use this one: https://help.voicefoundry.cloud/zendesk/Zendesk-Search-for-Connect-with-the-help-of-the-Zendesk-Support-API.2279221300.html

Thanks,
Andrej
