### ISSUE TITLE
How to identify customer by custom field

### ISSUE THREAD

**Issue by barbuuu** [voicefoundryap/amazon-connect-for-zendesk#90]
Hi Dev team,
My goal is to identify the customer when call is received by a custom field. In Amazon connect call flow I give to the caller the option to type his identification number (SAP ID) and I want to use this custom field to identify the customer once call is received in Zendesk.

Under People I create a custom field named SAP ID with field key sap_id. What attribute should I use in Amazon Connect to send this custom field to Zendesk when the caller tipe his SAP ID code?
Zendesk:
![image](https://user-images.githubusercontent.com/44302559/184305350-46416a52-a0ba-4f4b-9a56-11a31c81450d.png)

Amazon Connect:
![image](https://user-images.githubusercontent.com/44302559/184305685-6f5378de-f649-44a4-92c9-d230dc9f1bd9.png)

P.S. I read the documentation and I have tried all posible combinations but nothing is working.

Can you please gave me an example based on my sap_id custom field?

Most appreciated !
Dan Barbu

**Comment by agroblervf** [comment]
Hi Dan,

Custom fields are supported via our Zendesk Search add-on.
Please see this guide: https://help.voicefoundry.cloud/zendesk/zendesk-search-for-connect-with-the-help-of-the-ze
for more information.

Kind regards,
Andrej

**Comment by barbuuu** [comment]
Hi Andrej,

Most appreciated. From where I can install this Zendesk Search add-on? I can't find it by this name on Marketplace. Can you point me to the install page please?

**Comment by barbuuu** [comment]
found it thanks ! I must install it on Amazon Connect... my bad
