### ISSUE TITLE
[Bug] Chat incoming Issue

### ISSUE THREAD

**Issue by gsn-kimhanmiru** [voicefoundryap/amazon-connect-for-zendesk#91]
**Describe the bug**
Error when incoming from ccp for Connect chat channel.
We uploaded the provided zendesk app without modification.

I also updated the connect-stream.js file to the latest file and tested it, but the symptoms are the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/96461203/199423168-74fe6398-c13c-4d09-a0c3-65246c8e4321.png)
![image](https://user-images.githubusercontent.com/96461203/199423259-e4f397aa-d8d3-4efd-bbaa-be1100c3c66d.png)

**Comment by agroblervf** [comment]
Please note, this Repo is no longer being updated with the latest version of Amazon Connect for Zendesk app.
Please install it from [Zendesk marketplace](https://www.zendesk.com/marketplace/apps/support/243469/amazon-connect/), the latest version supports chat.
