### ISSUE TITLE
[Bug] node_modules is missing from the latest package

### ISSUE THREAD

**Issue by watiko** [voicefoundryap/amazon-connect-for-zendesk#92]
**Describe the bug**
`node_modules` is missing from the latest package. As a result, `contact-lens` and `zendesk-search` Lambda terminates with a run-time error below.

```
Error: Cannot find module 'axios'
```

**To Reproduce**
1. Go to AWS Lambda console
2. Click on Create Application button
3. Find `Contact-Lens-Analysis-for-Zendesk`(or `Zendesk-search-for-Connect-contact-flows`)
4. Deploy it
5. Run it
6. See error

**Expected behavior**
`node_modules` should be packed with Lambda's code.

**Comment by agroblervf** [comment]
Hi Watiko,

Thanks for alerting us of this issue. This is now fixed. 
Updated packages of Zendesk Search and Contact Lens have been published to Serverless Application Repository and should now contain `node_modules` subfolder with required libraries. 
Please re-deploy the package at your convenience.
Let us know if any other issues.

Warm regards,
Andrej
