### ISSUE TITLE
[Bug] A problem that the mute function does not work properly when the value of 'allowFramedSoftphone' is set to false

### ISSUE THREAD

**Issue by kimhanmiru** [voicefoundryap/amazon-connect-for-zendesk#94]
**Describe the bug**
We are developing a softphone (ccp).
In accordance with the vdi environment guided by AWS, in the custom ccp of the vdi environment, the value of allowFramedSoftphone is set to false in the initCCP function.

So, I set it to media less.
However, clicking the mute button in ccp does not take effect.

How should I solve it?

**Expected behavior**
Clicking the mute button mutes it and should change to an unmute button, but nothing happens

**Environment (please complete the following information):**
 - OS: Amazon workspace Windows 10
 - Browser chrome
 - Version lastest

**Comment by agroblervf** [comment]
Hi @kimhanmiru,

This doesn't appear to be an issue related to this product (Amazon Connect app for Zendesk). If you believe it is, please raise it via this [Support Portal](https://voicefoundry-au.atlassian.net/servicedesk/customer/portal/16).
From your description - if you're developing your own product using custom CCP and connect-streams library, you should contact AWS support.

Kind regards.
