### ISSUE TITLE
I can see in the docs a newer releases not in github? 

### ISSUE THREAD

**Issue by afryer** [voicefoundryap/amazon-connect-for-zendesk#95]
I can see in the docs

https://help.voicefoundry.cloud/zendesk/release-2-3-2

but there is not the corresponding release in github? Has the licensing and direction of this changed? 

Is the new release planned to be released open?

**Comment by karl-mentzer-vf** [comment]
Hello,

Yes there have been some changes to the IP ownership of the code.
This repo is no longer being maintained and will soon be set to private.
